language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install nose
  - pip install mock
  - pip install requests
  - pip install coveralls
script: nosetests --with-coverage --cover-package=fbmessenger
after_success:
  - coveralls
